### PR TITLE
Upgrade docker cloud-builder to 19.03.1

### PR DESCRIPTION
**Pull request by mareksuscak**

### CODE REVIEW

**Comment by ImJasonH** [comment]
Hi @mareksuscak, thanks for your PR. While we wait for this to be reviewed/merged/released, I actually just merged https://github.com/GoogleCloudPlatform/cloud-builders/pull/493 which documents that you can use the official `docker` images today, tagged with whatever client version you want:

```
steps:
- name: docker:19.03.1
  args: ['build', '-t', '...']
```

**Comment by mareksuscak** [comment]
This is awesome, thanks @ImJasonH

**Comment by tsloughter** [comment]
Is the plan to stick to 18.06?

I as because 19.03 comes with the new build tool `buildx` for docker but simply using `name: docker:19.03.1` does not work to use it.

Trying to use `docker buildx` directly says it does not exist while trying to use new features results in errors like, `"--output" requires API version 1.40, but the Docker daemon API version is 1.39`

**Comment by tsloughter** [comment]
And buildkit doesn't work, or at least experimental syntax for it doesn't work as mentioned in this issue https://github.com/GoogleCloudPlatform/cloud-builders/issues/506

**Comment by jeremywadsack** [comment]
It would be great to get both the client and the daemon updated. The Docker versions are really old. The workarounds listed in #506 get most of the way there but `--cache-from` doesn't work because (as far as I can tell) because the daemon (server) is out of data. See moby/moby#40262.

**Comment by lukas1994** [comment]
is this gonna let me use `DOCKER_BUILDKIT=1`? when are you planning to merge this?

**Comment by tsloughter** [comment]
It is certainly annoying having to keep multiple Dockerfiles in projects because cloudbuild doesn't support the latest stable version.

**Comment by bendory** [comment]
Closing as obsolete, reference https://github.com/GoogleCloudPlatform/cloud-builders/pull/654

**Pull request closed without merging**
