### PR TITLE
Use docker-credential-gcr for docker authentication.

### PR DESCRIPTION
**Pull request by skelterjohn**

### CODE REVIEW

**Comment by skelterjohn** [comment]
Note that this won't go into effect until we stop volume-mounting the credential file into build steps, since it depends on the contents of that file remaining fixed as they are in the image.

**Comment by bendory** [comment]
Note: @skelterjohn and I discussed off-line; there are a number of unresolved issues with this PR that need to be resolved prior to merge.

**Comment by ImJasonH** [comment]
Is this PR still active?

**Comment by skelterjohn** [comment]
nope!

**Pull request closed without merging**
