### PR TITLE
Add go version 1.19 alongside other tags

### PR DESCRIPTION
**Pull request by chadwpetersen**
This adds a cloud builder for `Go 1.19`.

### CODE REVIEW

**Comment by hazim1093** [comment]
Would be really nice if this is merged, the current go version is quite old

**Comment by juniocezar** [comment]
Hi @leeonlee . Could we have you or someone else looking at this? Tagging you as you were involved with the inclusion of Golang 1.18 in the PR https://github.com/GoogleCloudPlatform/cloud-builders/pull/827. I hope this doesn't annoy you.

**Comment by leeonlee** [comment]
I just got back from parental leave and it looks like my permissions have lapsed :) I'll try to get myself added tomorrow or I'll have somebody else review.

**Review by arvinddayal — APPROVED** [review]

**Comment by hazim1093** [comment]
Thank you for the quick response @juniocezar @leeonlee @arvinddayal :) 
I created another similar PR for go version 1.20 as well, since that is out 
https://github.com/GoogleCloudPlatform/cloud-builders/pull/891

**Pull request merged**
