### PR TITLE
Bump Node 10 to the LTS version in Yarn

### PR DESCRIPTION
**Pull request by charud**
Bumps Node 10.10.0 to 10.15.3 (LTS)

### CODE REVIEW

**Comment by charlie-rudenstal** [comment]
I signed it!

**Comment by elizabeth-dev** [comment]
It seems that this Cloud Builder image is deprecated. I was writing a PR to add 11.x and 12.x versions when I saw this. Bad news, it would be really useful for saving some Cloud Build seconds, instead of pulling official Node.js image.

**Comment by mehdime** [comment]
Are there any guidelines on how to contribute updated versions of these images? Having a more recent version of Node available would be handy but that PR seems to have been stuck here for a few months now.

**Comment by elizabeth-dev** [comment]
@mehdime I just forked the repo (privately), and built a custom image in my own container registry namespace adding the desired versions.

**Comment by bendory** [comment]
closing as obsolete; reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/322

**Pull request closed without merging**
