### PR TITLE
Install all components in gcloud builder image

### PR DESCRIPTION
**Pull request by ImJasonH**

### CODE REVIEW

**Comment by Philmod** [comment]
What's the increased size?

**Comment by dgageot** [comment]
882Mb to 1.96Gb...

**Comment by ImJasonH** [comment]
`gcloud components install` reports that the new components should only be ~400MB:
```
Step #0: +-------------------------------------------------------------------------------+
Step #0: |                      These components will be installed.                      |
Step #0: +------------------------------------------------------+------------+-----------+
Step #0: |                         Name                         |  Version   |    Size   |
Step #0: +------------------------------------------------------+------------+-----------+
Step #0: | App Engine Go Extensions                             |     1.9.63 | 151.9 MiB |
Step #0: | Cloud Bigtable Command Line Tool                     |      0.2.3 |   4.5 MiB |
Step #0: | Cloud Bigtable Emulator                              | 2018.01.05 |   3.7 MiB |
Step #0: | Cloud Datalab Command Line Tool                      |   20180213 |   < 1 MiB |
Step #0: | Cloud Datalab Command Line Tool (Platform Specific)  |   20170818 |   < 1 MiB |
Step #0: | Cloud Datastore Emulator                             |      1.4.1 |  17.9 MiB |
Step #0: | Cloud Pub/Sub Emulator                               | 2018.02.02 |  33.4 MiB |
Step #0: | Emulator Reverse Proxy                               |      0.0.1 |  14.5 MiB |
Step #0: | Google Container Local Builder                       |      0.2.6 |   3.8 MiB |
Step #0: | Google Container Registry's Docker credential helper |      1.4.3 |   3.3 MiB |
Step #0: | gRPC python library                                  |      1.9.1 |  12.1 MiB |
Step #0: | gcloud app Java Extensions                           |     1.9.62 | 118.8 MiB |
Step #0: | gcloud app PHP Extensions                            |            |           |
Step #0: | gcloud app Python Extensions                         |     1.9.67 |   6.2 MiB |
Step #0: | gcloud app Python Extensions (Extra Libraries)       |     1.9.63 |  27.8 MiB |
Step #0: +------------------------------------------------------+------------+-----------+
```

But alas, the image is indeed >1GB larger:
```
$ docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
gcr.io/xxxxxxxxx/gcloud        latest              915a94839ae3        7 minutes ago       1.96GB
gcr.io/cloud-builders/gcloud   latest              7e26d870a91d        6 hours ago         882MB
```

**Comment by bendory** [comment]
Is the extra ~600M (expected ~400M, got ~1G) implied dependencies?

**Comment by ImJasonH** [comment]
Maybe, yeah. It could also be a disconnect about compressed vs uncompressed size. `gcloud components install` might be reporting compressed size of components you're about to install, then decompressing them during installation.

I'm fairly certain whatever it is it's not anything "unexpected" creeping into the image, I'm just installing all the components and they happen to add ~1G to the size.

**Comment by ImJasonH** [comment]
Ping

**Pull request merged**
