### PR TITLE
Fix bug where missing KUBECTL env var leads to bad `kubectl` command

### LINKED ISSUE #581: cloud-builders/kubectl fails without KUBECTL_VERSION
## Affected builder image

gcr.io/cloud-builders/kubectl

## Expected Behavior

Container image should work without setting the `KUBECTL_VERSION` environment variable.

## Actual Behavior

Cloud build logs:
```
Fetching cluster endpoint and auth data.
kubeconfig entry generated for [cluster name elided].
Running: kubectl. apply -f deployment/k8s
/builder/kubectl.bash: line 40: exec: kubectl.: not found
```

## Steps to Reproduce the Problem

1. Run your existing cloud build deployments with the new image (the `:latest` tag.)

## Additional Info
https://github.com/GoogleCloudPlatform/cloud-builders/pull/574 added the option to use the `KUBECTL_VERSION` environment variable to select the version of `kubectl` to use. However it incorrectly selects the executable name when `KUBECTL_VERSION` is unset.

This makes the change backwards incompatible and breaks all existing deployments using this cloud-builder image.

### PR DESCRIPTION
**Pull request by jakebiesinger**
Fixes #581

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/cloud-builders/582)

### CODE REVIEW

**Comment by jakebiesinger** [comment]
Friendly ping here... cloud-builders/kubectl is broken until this gets merged :( :(

@ImJasonH care to take a look?

**Comment by benjamin-maynard** [comment]
> Friendly ping here... cloud-builders/kubectl is broken until this gets merged :( :(
> 
> @ImJasonH care to take a look?

+1 - We're quite heavily impacted by this.

**Comment by jakebiesinger-onduo** [comment]
Daily ping to get this fixed....

**Comment by Timor1986** [comment]
Please submit the fix..

**Comment by Timor1986** [comment]
Thank you, any chance you can assume when images will be updated?

**Comment by b3ntly** [comment]
Shouldn't customers have been notified of this continued "outage"? I understand mistakes happen, and this technically is a convenience library and not a traditional service under SLA (I think), but doesn't this impact EVERY cloud builder user depending on kubectl? 


Why does this change take so long to revert? And will process changes be made such that I can trust it not to silently break going forward?

**Comment by camh-anz** [comment]
I'm not sure when this went live, but I can confirm that `gcr.io/cloud-builders/kubectl:latest` contains the fix now. Thanks.

**Pull request merged**
