### PR TITLE
Moving git config above the go.mod check

### PR DESCRIPTION
**Pull request by mlesar**
#759

### CODE REVIEW

**Comment by bendory** [comment]
@mlesar This looks to me like a bug fix -- thank you!

Can you please provide a more extensive explanation of what the issue is and how this fixes it? Referencing an example would also be helpful. (A test case that fails before / passes with this PR would be the best example.)

Happy to see that explanation here in the PR, or equally happy to see you file a descriptive issue which is then fixed by this PR, whatever you prefer.

Will look to get this merged ASAP following the above.

Thank you!

**Comment by bendory** [comment]
Oh -- doh! -- looks like you indeed did most of the above already, I clearly should have noticed the attached issue. Would you mind please adding an example per my prior comment? (Either here or in the attached issue is fine.)

Thank you again!

**Comment by mlesar** [comment]
> Would you mind please adding an example per my prior comment?

Added an example to the issue, let me know if anything else is needed.

**Review by bendory — APPROVED** [review]

**Comment by bendory** [comment]
Thanks!

**Pull request merged**
