### PR TITLE
Upgrade node and npm version to newest current and LTS

### PR DESCRIPTION
**Pull request by tlbdk**

### CODE REVIEW

**Comment by Philmod** [comment]
@JustinBeckwith Should we still build the older versions?

**Comment by tlbdk** [comment]
We could add all supported versions and tag them with exact and major version:

Fx these tags:
4.8.7 and 4.x
6.12.2 and 6.x
8.9.3, 8.x and latest
9.3.0 9.x and current

https://github.com/nodejs/Release

**Comment by ofpiyush** [comment]
Can we merge this in? Waiting to use 8.9.0. Would love to cloud builder images as they mean shorter build times. :)

**Comment by chainlink** [comment]
+1 Would also love this

**Comment by ImJasonH** [comment]
I think it makes sense to keep building old versions for a bit. That way if someone is broken by 9.3 they can at least specify 8.4 to get the old "current" builder.

@tlbdk if you want to make that change in this PR that would be best, otherwise I'll merge this and send another PR shortly after to add the old latest/current versions.

**Comment by ofpiyush** [comment]
@ImJasonH the current versioned images will continue to be present and usable

Are you worried about updates to the underlying OS images etc?

**Comment by ImJasonH** [comment]
Yeah we'll keep building the old versions ~daily to pick up any underlying
changes, until we decide to stop and untag the image entirely.

**Comment by tlbdk** [comment]
@ImJasonH I won't have time to look at this the next couple of days so if you have time it would be great

**Comment by ImJasonH** [comment]
See #192 which adds the new versions but doesn't update `:latest` and `:current` just yet.

**Pull request closed without merging**
