### PR TITLE
add support for maven 3.6.0

### PR DESCRIPTION
**Pull request by etsrepo**
Hi,

Added support for maven 3.6.0. 

changed sha256sum to sha512sum, because maven 3.6.0 distributing sha512 in official maven site. I have recalculated sha512sum for 3.5.0 and 3.3.9 and updated docker file accordingly.

Ref:
https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz.sha512
https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/

### CODE REVIEW

**Comment by etsrepo** [comment]
I will all add java 11 support if https://github.com/GoogleCloudPlatform/cloud-builders/pull/437 is accepted

**Comment by etsrepo** [comment]
fixes https://github.com/GoogleCloudPlatform/cloud-builders/issues/412 if this and https://github.com/GoogleCloudPlatform/cloud-builders/pull/437 merged

**Comment by ImJasonH** [comment]
cc @loosebazooka

To avoid the need for these updates long-term, what do we think about making the image `FROM maven:$VERSION` and recommending people use the [official maven image](https://hub.docker.com/_/maven) directly?

```
steps
- name: maven:whatever-version-you-want
  args: ['--version']
```

This has been done for npm and yarn in #326 and I think it's been a positive change.

**Comment by ImJasonH** [comment]
FWIW #451 updates the `mvn` builder to be `FROM maven:$VERSION` and recommends just using the `maven` image directly. Once that gets merged I'm not sure we need this PR, unless there's some reason you'd strongly prefer it.

**Comment by ImJasonH** [comment]
@etsrepo `maven:latest` (which is currently `maven:3.6.0`) is already cached, so this PR should be unnecessary if you can just use the `maven` image directly.

Please let me know if this is incorrect or if you need anything else.

**Comment by etsrepo** [comment]
@ImJasonH I agree on using official/direct images. thank you.

**Pull request closed without merging**
