### PR TITLE
feat(npm): update node to latest version

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
This includes security releases.

Let me know if I missed something since first PR.

### CODE REVIEW

**Comment by ImJasonH** [comment]
This change LGTM, but we should more forcefully recommend people use the official node/yarn images directly, so these kinds of PRs are not necessary.

**Comment by AdriVanHoudt** [comment]
I guess that is on your end, if you intent to merge I can update those to the latest version before you do

**Comment by ImJasonH** [comment]
Yeah, let's upgrade to the latest available versions in the hopes that they're the last we have to support this way.

#451 addresses more forcefully recommending official images for mvn/npm/yarn

**Comment by ImJasonH** [comment]
We're going to recommend users run the official `node` image directly, which currently points to `11.9.0` and which is already cached on worker images.

Over time we can upgrade the `npm` and `yarn` builders to just be `FROM node` (latest) and remove a lot from these builders' configs.

**Comment by AdriVanHoudt** [comment]
Cool, I will use that then, thanks!

**Pull request closed without merging**
