### PR TITLE
Add builder support for .NET Core 2.1

### LINKED ISSUE #288: Add support for dotnet core 2.1 build
[ASP.Net Core 2.1 was just officialy released](https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/). After i upgraded my ASP.Net project to 2.1, i am not longer able to use your cloud-build tool dotnet to automatically run my tests. It seems to be confirmed by [your documentation](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/dotnet) that it is not yet supported.

`gcr.io/cloud-builders/dotnet test [my-dotnetcore2.1-project]`

gives

/usr/share/dotnet/sdk/2.1.4/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [/workspace/[MyProject].Tests/[MyProject].Tests.csproj]

### PR DESCRIPTION
**Pull request by ILMTitan**
Update the .NET Core SDK 2.1 version to 2.1.300.
Add tests to the build to ensure the `dotnet` image can compile the example projects.
Fixes #288

### CODE REVIEW

**Comment by henkmollema** [comment]
What is the ETA on publishing this to GCR? 😄

**Comment by bendory** [comment]
@henkmollema Once the PR is merged, it's typically 1-2 business days before publishing the resultant container to GCR as "latest". Note that if you want to use this change before then, you can always build it yourself and push the image to your own project.

**Comment by henkmollema** [comment]
Thanks! I've pushed to my project's GCR for now indeed.

**Comment by ILMTitan** [comment]
@bendory What do I need to do to get this reviewed and merged? I don't have access to setting reviewers.

**Pull request merged**
